name: Lintererer

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      uses: dschep/install-pipenv-action@v1
    - name: Install dependencies
      run: pipenv install --python ${{ matrix.python-version }}
    - name: Run linter
      run: pipenv run pylint $(git ls-files '*.py') --fail-under=9 --py-version=${{ matrix.python-version }}